In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset_tr=pd.read_csv('SalaryData_Train.csv')
dataset_te=pd.read_csv('SalaryData_Test.csv')

In [3]:
dataset_tr

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [4]:
dataset_te

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[15060 rows x 14 columns]

In [5]:
dataset_tr['workclass'].nunique()

7

### Loop to find number of unique values to identify the irrelevant independent variables

In [6]:
for c in dataset_tr.columns:
    print ("---- %s ---" % c)
    print (dataset_tr[c].nunique())

---- age ---
72
---- workclass ---
7
---- education ---
16
---- educationno ---
16
---- maritalstatus ---
7
---- occupation ---
14
---- relationship ---
6
---- race ---
5
---- sex ---
2
---- capitalgain ---
118
---- capitalloss ---
90
---- hoursperweek ---
94
---- native ---
40
---- Salary ---
2


### Deleting irrelevant columns

In [7]:
dataset_te.drop(['age','educationno','capitalgain','capitalloss','hoursperweek','native'],axis=1,inplace=True)
dataset_tr.drop(['age','educationno','capitalgain','capitalloss','hoursperweek','native'],axis=1,inplace=True)

In [10]:
dataset_tr

workclass    education        maritalstatus  \
0              State-gov    Bachelors        Never-married   
1       Self-emp-not-inc    Bachelors   Married-civ-spouse   
2                Private      HS-grad             Divorced   
3                Private         11th   Married-civ-spouse   
4                Private    Bachelors   Married-civ-spouse   
...                  ...          ...                  ...   
30156            Private   Assoc-acdm   Married-civ-spouse   
30157            Private      HS-grad   Married-civ-spouse   
30158            Private      HS-grad              Widowed   
30159            Private      HS-grad        Never-married   
30160       Self-emp-inc      HS-grad   Married-civ-spouse   

               occupation    relationship    race      sex  Salary  
0            Adm-clerical   Not-in-family   White     Male   <=50K  
1         Exec-managerial         Husband   White     Male   <=50K  
2       Handlers-cleaners   Not-in-family   White     Male   <=50K  
3       Handlers-cleaners         Husband   Black     Male   <=50K  
4          Prof-specialty            Wife   Black   Female   <=50K  
...                   ...             ...     ...      ...     ...  
30156        Tech-support            Wife   White   Female   <=50K  
30157   Machine-op-inspct         Husband   White     Male    >50K  
30158        Adm-clerical       Unmarried   White   Female   <=50K  
30159        Adm-clerical       Own-child   White     Male   <=50K  
30160     Exec-managerial            Wife   White   Female    >50K  

[30161 rows x 8 columns]

### Separate dependent and independent variable

In [11]:
x_train=dataset_tr.iloc[:,:-1]
y_train=dataset_tr.iloc[:,-1]
x_test=dataset_te.iloc[:,:-1]
y_test=dataset_te.iloc[:,-1]

In [12]:
x_train

workclass    education        maritalstatus  \
0              State-gov    Bachelors        Never-married   
1       Self-emp-not-inc    Bachelors   Married-civ-spouse   
2                Private      HS-grad             Divorced   
3                Private         11th   Married-civ-spouse   
4                Private    Bachelors   Married-civ-spouse   
...                  ...          ...                  ...   
30156            Private   Assoc-acdm   Married-civ-spouse   
30157            Private      HS-grad   Married-civ-spouse   
30158            Private      HS-grad              Widowed   
30159            Private      HS-grad        Never-married   
30160       Self-emp-inc      HS-grad   Married-civ-spouse   

               occupation    relationship    race      sex  
0            Adm-clerical   Not-in-family   White     Male  
1         Exec-managerial         Husband   White     Male  
2       Handlers-cleaners   Not-in-family   White     Male  
3       Handlers-cleaners         Husband   Black     Male  
4          Prof-specialty            Wife   Black   Female  
...                   ...             ...     ...      ...  
30156        Tech-support            Wife   White   Female  
30157   Machine-op-inspct         Husband   White     Male  
30158        Adm-clerical       Unmarried   White   Female  
30159        Adm-clerical       Own-child   White     Male  
30160     Exec-managerial            Wife   White   Female  

[30161 rows x 7 columns]

In [13]:
x_test

workclass      education        maritalstatus          occupation  \
0            Private           11th        Never-married   Machine-op-inspct   
1            Private        HS-grad   Married-civ-spouse     Farming-fishing   
2          Local-gov     Assoc-acdm   Married-civ-spouse     Protective-serv   
3            Private   Some-college   Married-civ-spouse   Machine-op-inspct   
4            Private           10th        Never-married       Other-service   
...              ...            ...                  ...                 ...   
15055        Private      Bachelors        Never-married      Prof-specialty   
15056        Private      Bachelors             Divorced      Prof-specialty   
15057        Private      Bachelors   Married-civ-spouse      Prof-specialty   
15058        Private      Bachelors             Divorced        Adm-clerical   
15059   Self-emp-inc      Bachelors   Married-civ-spouse     Exec-managerial   

         relationship                 race      sex  
0           Own-child                Black     Male  
1             Husband                White     Male  
2             Husband                White     Male  
3             Husband                Black     Male  
4       Not-in-family                White     Male  
...               ...                  ...      ...  
15055       Own-child                White     Male  
15056   Not-in-family                White   Female  
15057         Husband                White     Male  
15058       Own-child   Asian-Pac-Islander     Male  
15059         Husband                White     Male  

[15060 rows x 7 columns]

In [31]:
y_train

0         <=50K
1         <=50K
2         <=50K
3         <=50K
4         <=50K
          ...  
30156     <=50K
30157      >50K
30158     <=50K
30159     <=50K
30160      >50K
Name: Salary, Length: 30161, dtype: object

In [32]:
y_test

0         <=50K
1         <=50K
2          >50K
3          >50K
4         <=50K
          ...  
15055     <=50K
15056     <=50K
15057     <=50K
15058     <=50K
15059      >50K
Name: Salary, Length: 15060, dtype: object

### Converting independent variable to 0,1,2.....

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
string_columns=x_train.columns
for i in string_columns:
    x_train[i]=le.fit_transform(x_train[i])
    x_train[i]=le.fit_transform(x_train[i])

<ipython-input-21-f1f8a5e82ef1>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i]=le.fit_transform(x_train[i])
<ipython-input-21-f1f8a5e82ef1>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[i]=le.fit_transform(x_train[i])


In [29]:
string_columns1=x_test.columns
for i in string_columns1:
    x_test[i]=le.fit_transform(x_test[i])
    x_test[i]=le.fit_transform(x_test[i])

<ipython-input-29-eed963c9cb61>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i]=le.fit_transform(x_test[i])
<ipython-input-29-eed963c9cb61>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[i]=le.fit_transform(x_test[i])


In [30]:
x_test

workclass  education  maritalstatus  occupation  relationship  race  \
0              2          1              4           6             3     2   
1              2         11              2           4             0     4   
2              1          7              2          10             0     4   
3              2         15              2           6             0     2   
4              2          0              4           7             1     4   
...          ...        ...            ...         ...           ...   ...   
15055          2          9              4           9             3     4   
15056          2          9              0           9             1     4   
15057          2          9              2           9             0     4   
15058          2          9              0           0             3     1   
15059          3          9              2           3             0     4   

       sex  
0        1  
1        1  
2        1  
3        1  
4        1  
...    ...  
15055    1  
15056    0  
15057    1  
15058    1  
15059    1  

[15060 rows x 7 columns]

### Encoding Dependent Variable

In [33]:
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

In [34]:
y_train

array([0, 0, 0, ..., 0, 0, 1])

In [35]:
y_test

array([0, 0, 1, ..., 0, 0, 1])

### Model Building

In [36]:
from sklearn.naive_bayes import GaussianNB
Gmodel=GaussianNB()


In [37]:
Gmodel.fit(x_train,y_train)

GaussianNB()

In [39]:
y_pred=Gmodel.predict(x_test)

In [41]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 0]
 [1 1]
 ...
 [1 0]
 [0 0]
 [1 1]]


### Confusion Matrix

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[8692 2668]
 [1138 2562]]


0.7472775564409031